### ISSUE TITLE
Cannot import F:\ComfyUI_1228\ComfyUI\custom_nodes\ComfyUI-StableDiffusion3-API module for custom nodes: closing parenthesis '}' does not match opening parenthesis '(' (sd3api.py, line 51)

### ISSUE THREAD

**Issue by chenjiu2008** [ZHO-ZHO-ZHO/ComfyUI-StableDiffusion3-API#3]
Cannot import F:\ComfyUI_1228\ComfyUI\custom_nodes\ComfyUI-StableDiffusion3-API module for custom nodes: closing parenthesis '}' does not match opening parenthesis '(' (sd3api.py, line 51)

**Comment by Jeremy8776** [comment]
Yeah there is an extra   --> } <-- on line 51 just delete one of the two and should be good to go

**Comment by chenjiu2008** [comment]
> Yeah there is an extra --> } <-- on line 51 just delete one of the two and should be good to go是的，在第 51 行有一个额外的 --> } <-- 只需删除两个中的一个，就可以了

thank you,it works.
